"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
final_space = true
version = 3

[[blocks]]
type = "prompt"
alignment = "left"

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#a6e3a1"
  template = "["


  [[blocks.segments]]
  foreground = "#43CCEA"
  foreground_templates = [
  "{{ if or (.Working.Changed) (.Staging.Changed) }}#FF9248{{ end }}",
  "{{ if and (gt .Ahead 0) (gt .Behind 0) }}#ff4500{{ end }}",
  "{{ if gt .Ahead 0 }}#B388FF{{ end }}",
  "{{ if gt .Behind 0 }}#B388FF{{ end }}"
  ]
  style = "plain"
  template = "{{ if and (ne .Ref \"main\") (ne .Ref \"master\") }}{{ .Ref }}{{end}}{{ if .Working.Changed }}{{ .Working.String}}{{ end }}{{ if and (.Working.Changed) (.Staging.Changed) }}|{{ end }}{{ if .Staging.Changed }}{{ .Staging.String }}{{ end }}{{ if gt .StashCount 0 }}{{ .StashCount }}{{ end }} "
  type = "git"

    [blocks.segments.properties]
    branch_max_length = 25
    fetch_stash_count = true
    fetch_status = true
    fetch_upstream_icon = true
   
  [[blocks.segments]]
  type = "python"
  style = "plain"
  template = "({{ if .Error }}{{ .Error }}{{ else }}{{ if .Venv }}{{ .Venv }}{{ end }}{{ end }}) "
  
[[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#a6e3a1"
  template = "{{if .Env.SSH_TTY }}{{.UserName}}@{{.HostName }}{{end}} "


  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = ""
  template = "{{.PWD}}"
  
  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#ff0000"
  template = "{{if gt .Code 0}} {{.Code}}{{end}}"

  [[blocks.segments]]
  foreground = "#AEA4BF"
  style = "plain"
  template = " {{ .FormattedMs }}"
  type = "executiontime"

    [blocks.segments.properties]
    threshold = 150

  [[blocks.segments]]
  type = "text"
  style = "plain"
  foreground = "#a6e3a1"
  template = "]"
  
[[blocks.segments]]
  type = "text"
  style = "plain"
  foreground_templates = ["{{if .Root }}#FF0000{{else}}#04a5e5{{end}}"]
  template = "{{if .Root}}#{{else}}${{end}}"
